name: SentinelLite
version: '${version}'
main: me.trouper.sentinellite.SentinelLite
api-version: 1.21
authors: [ TheTrouper ]
description: Sentinel without the bare essentials.
website: https://thetrouper.github.io/
load: STARTUP
permissions:
  sentinellite.admin:
    description: Allows access to all SentinelLite admin commands.
    default: op
    children:
      sentinellite.reload: true
      sentinellite.config: true
      sentinellite.debug: true
  sentinellite.staff:
    description: Allows access to Sentinel staff commands.
    default: op
    children:
      sentinellite.socialspy: true
  sentinellite.socialspy:
    description: Allows the user to spy on social interactions.
    default: false
  sentinellite.reload:
    description: Allows the user to reload SentinelLite.
    default: false
  sentinellite.debug:
    description: Allows the user to toggle debug mode.
    default: false
  sentinellite.message:
    description: Allows the user to send messages.
    default: true
  sentinellite.reply:
    description: Allows the user to reply to messages.
    default: true
  sentinellite.chatfilter:
    description: Parent permission for all chat-related features.
    default: false
    children:
      sentinellite.chatfilter.profanity: true
  sentinellite.chatfilter.profanity:
    description: Parent permission for profanity filter features.
    default: false
    children:
      sentinellite.chatfilter.profanity.view: true
      sentinellite.chatfilter.profanity.bypass: true
  sentinellite.chatfilter.profanity.view:
    description: Allows the user to view profanity filter logs.
    default: false
  sentinellite.chatfilter.profanity.bypass:
    description: Allows the user to bypass the profanity filter.
    default: false
commands:
  sentinellite:
    description: Main command for SentinelLite.
    usage: /sentinel <reload|debug|socialspy>
    permission: sentinellite.staff
    permission-message: You do not have permission to use this command.
  message:
    description: Send a message to another player.
    usage: /message <player> <message>
    permission: sentinellite.message
    permission-message: You do not have permission to use this command.
    aliases:
      - msg
      - etell
      - tell
      - t
      - ewhisper
      - whisper
      - w
      - privatemessage
      - pm
      - m
      - directmessage
      - dm
      - sentinelmessage
      - sm
      - stell
      - smsg
  reply:
    description: Reply to a message.
    usage: /reply <message>
    permission: sentinellite.reply
    permission-message: You do not have permission to use this command.
    aliases:
      - r
      - er
      - rply
      - ereply
      - sr
      - sreply
      - sentinelreply
  reop:
    description: Allows trusted players to elevate their permissions
    usage: /reop